#include "../include/user_config.h"

void ICACHE_FLASH_ATTR spi_init() {
	//CLEAR_PERI_REG_MASK(SPI_CTRL(1), SPI_FASTRD_MODE);
	SET_PERI_REG_MASK(SPI_CTRL(1), SPI_WR_BIT_ORDER);
	CLEAR_PERI_REG_MASK(SPI_CLOCK(1),
			SPI_CLK_EQU_SYSCLK|(SPI_CLKDIV_PRE << SPI_CLKDIV_PRE_S)|(SPI_CLKCNT_N << SPI_CLKCNT_N_S)|(SPI_CLKCNT_H << SPI_CLKCNT_H_S)|(SPI_CLKCNT_L << SPI_CLKCNT_L_S));
	SET_PERI_REG_MASK(SPI_CLOCK(1),
			((0x00&SPI_CLKDIV_PRE) << SPI_CLKDIV_PRE_S)|((0x04&SPI_CLKCNT_N) << SPI_CLKCNT_N_S)|((0x04&SPI_CLKCNT_H) << SPI_CLKCNT_H_S)|((0x01&SPI_CLKCNT_L) << SPI_CLKCNT_L_S));
	CLEAR_PERI_REG_MASK(SPI_USER(1), SPI_USR_COMMAND|SPI_FLASH_MODE);
	SET_PERI_REG_MASK(SPI_USER(1), SPI_USR_MOSI);
	CLEAR_PERI_REG_MASK(SPI_USER1(1),
			(SPI_USR_ADDR_BITLEN << SPI_USR_ADDR_BITLEN_S));
	SET_PERI_REG_MASK(SPI_USER1(1), (383 << SPI_USR_MOSI_BITLEN_S));
	CLEAR_PERI_REG_MASK(SPI_USER2(1),
			(SPI_USR_COMMAND_BITLEN << SPI_USR_COMMAND_BITLEN_S));
	CLEAR_PERI_REG_MASK(SPI_PIN(1), SPI_CS0_DIS);
	SET_PERI_REG_MASK(SPI_SLAVE(1), SPI_TRANS_DONE_EN);
	CLEAR_PERI_REG_MASK(SPI_SLAVE(0), 0x3ff);
	PIN_FUNC_SELECT(PERIPHS_IO_MUX_MTCK_U, FUNC_HSPID_MOSI);
	PIN_FUNC_SELECT(PERIPHS_IO_MUX_MTMS_U, FUNC_HSPI_CLK);
	CLEAR_PERI_REG_MASK(PERIPHS_IO_MUX, BIT9);
}
